### ISSUE TITLE
missing key:  bn1.num_batches_tracked missing key:  layer1.0.downsample.1.num_batches_tracked missing key:  layer1.0.bn1.num_batches_tracked missing key:  layer1.0.bn2.num_batches_tracked missing key:  layer1.0.bn3.num_batches_tracked missing key:  layer1.1.bn1.num_batches_tracked missing key:  layer1.1.bn2.num_batches_tracked missing key:  layer1.1.bn3.num_batches_tracked

### ISSUE THREAD

**Issue by silencedog** [lhaof/Motion-Guided-Attention#4]
When I input python inference.py  I encounter prblem: missing key:  bn1.num_batches_tracked
missing key:  layer1.0.downsample.1.num_batches_tracked
missing key:  layer1.0.bn1.num_batches_tracked
missing key:  layer1.0.bn2.num_batches_tracked
missing key:  layer1.0.bn3.num_batches_tracked
missing key:  layer1.1.bn1.num_batches_tracked
missing key:  layer1.1.bn2.num_batches_tracked
missing key:  layer1.1.bn3.num_batches_tracked
missing key:  layer1.2.bn1.num_batches_tracked
missing key:  layer1.2.bn2.num_batches_tracked
missing key:  layer1.2.bn3.num_batches_tracked
missing key:  layer2.0.downsample.1.num_batches_tracked
missing key:  layer2.0.bn1.num_batches_tracked
missing key:  layer2.0.bn2.num_batches_tracked
missing key:  layer2.0.bn3.num_batches_tracked
missing key:  layer2.1.bn1.num_batches_tracked
missing key:  layer2.1.bn2.num_batches_tracked
missing key:  layer2.1.bn3.num_batches_tracked
missing key:  layer2.2.bn1.num_batches_tracked
missing key:  layer2.2.bn2.num_batches_tracked
missing key:  layer2.2.bn3.num_batches_tracked
missing key:  layer2.3.bn1.num_batches_tracked
missing key:  layer2.3.bn2.num_batches_tracked
missing key:  layer2.3.bn3.num_batches_tracked
missing key:  layer3.0.downsample.1.num_batches_tracked
missing key:  layer3.0.bn1.num_batches_tracked
missing key:  layer3.0.bn2.num_batches_tracked
missing key:  layer3.0.bn3.num_batches_tracked
missing key:  layer3.1.bn1.num_batches_tracked
missing key:  layer3.1.bn2.num_batches_tracked
missing key:  layer3.1.bn3.num_batches_tracked
missing key:  layer3.2.bn1.num_batches_tracked
missing key:  layer3.2.bn2.num_batches_tracked
missing key:  layer3.2.bn3.num_batches_tracked
missing key:  layer3.3.bn1.num_batches_tracked
missing key:  layer3.3.bn2.num_batches_tracked
missing key:  layer3.3.bn3.num_batches_tracked
missing key:  layer3.4.bn1.num_batches_tracked
missing key:  layer3.4.bn2.num_batches_tracked
missing key:  layer3.4.bn3.num_batches_tracked
missing key:  layer3.5.bn1.num_batches_tracked
missing key:  layer3.5.bn2.num_batches_tracked
missing key:  layer3.5.bn3.num_batches_tracked
missing key:  layer3.6.bn1.num_batches_tracked
missing key:  layer3.6.bn2.num_batches_tracked
missing key:  layer3.6.bn3.num_batches_tracked
missing key:  layer3.7.bn1.num_batches_tracked
missing key:  layer3.7.bn2.num_batches_tracked
missing key:  layer3.7.bn3.num_batches_tracked
missing key:  layer3.8.bn1.num_batches_tracked
missing key:  layer3.8.bn2.num_batches_tracked
missing key:  layer3.8.bn3.num_batches_tracked
missing key:  layer3.9.bn1.num_batches_tracked
missing key:  layer3.9.bn2.num_batches_tracked
missing key:  layer3.9.bn3.num_batches_tracked
missing key:  layer3.10.bn1.num_batches_tracked
missing key:  layer3.10.bn2.num_batches_tracked
missing key:  layer3.10.bn3.num_batches_tracked
missing key:  layer3.11.bn1.num_batches_tracked
missing key:  layer3.11.bn2.num_batches_tracked
missing key:  layer3.11.bn3.num_batches_tracked
missing key:  layer3.12.bn1.num_batches_tracked
missing key:  layer3.12.bn2.num_batches_tracked
missing key:  layer3.12.bn3.num_batches_tracked
missing key:  layer3.13.bn1.num_batches_tracked
missing key:  layer3.13.bn2.num_batches_tracked
missing key:  layer3.13.bn3.num_batches_tracked
missing key:  layer3.14.bn1.num_batches_tracked
missing key:  layer3.14.bn2.num_batches_tracked
missing key:  layer3.14.bn3.num_batches_tracked
missing key:  layer3.15.bn1.num_batches_tracked
missing key:  layer3.15.bn2.num_batches_tracked
missing key:  layer3.15.bn3.num_batches_tracked
missing key:  layer3.16.bn1.num_batches_tracked
missing key:  layer3.16.bn2.num_batches_tracked
missing key:  layer3.16.bn3.num_batches_tracked
missing key:  layer3.17.bn1.num_batches_tracked
missing key:  layer3.17.bn2.num_batches_tracked
missing key:  layer3.17.bn3.num_batches_tracked
missing key:  layer3.18.bn1.num_batches_tracked
missing key:  layer3.18.bn2.num_batches_tracked
missing key:  layer3.18.bn3.num_batches_tracked
missing key:  layer3.19.bn1.num_batches_tracked
missing key:  layer3.19.bn2.num_batches_tracked
missing key:  layer3.19.bn3.num_batches_tracked
missing key:  layer3.20.bn1.num_batches_tracked
missing key:  layer3.20.bn2.num_batches_tracked
missing key:  layer3.20.bn3.num_batches_tracked
missing key:  layer3.21.bn1.num_batches_tracked
missing key:  layer3.21.bn2.num_batches_tracked
missing key:  layer3.21.bn3.num_batches_tracked
missing key:  layer3.22.bn1.num_batches_tracked
missing key:  layer3.22.bn2.num_batches_tracked
missing key:  layer3.22.bn3.num_batches_tracked
missing key:  layer4.0.downsample.1.num_batches_tracked
missing key:  layer4.0.bn1.num_batches_tracked
missing key:  layer4.0.bn2.num_batches_tracked
missing key:  layer4.0.bn3.num_batches_tracked
missing key:  layer4.1.bn1.num_batches_tracked
missing key:  layer4.1.bn2.num_batches_tracked
missing key:  layer4.1.bn3.num_batches_tracked
missing key:  layer4.2.bn1.num_batches_tracked
missing key:  layer4.2.bn2.num_batches_tracked
missing key:  layer4.2.bn3.num_batches_tracked
missing key:  aspp.aspp1.bn.num_batches_tracked
missing key:  aspp.aspp2.bn.num_batches_tracked
missing key:  aspp.aspp3.bn.num_batches_tracked
missing key:  aspp.aspp4.bn.num_batches_tracked
missing key:  aspp.global_avg_pool.2.num_batches_tracked
missing key:  aspp.bn1.num_batches_tracked
missing key:  last_conv.1.num_batches_tracked
missing key:  last_conv.4.num_batches_tracked
missing key:  bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer1.0.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer1.0.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer1.1.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer1.1.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer1.2.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer1.2.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer2.0.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer2.0.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer2.0.downsample.1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer2.1.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer2.1.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer2.2.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer2.2.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer2.3.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer2.3.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.0.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.0.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.0.downsample.1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.1.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.1.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.2.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.2.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.3.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.3.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.4.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.4.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.5.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer3.5.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer4.0.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer4.0.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer4.0.downsample.1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer4.1.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer4.1.bn2.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer4.2.bn1.num_batches_tracked
missing key:  resnet_aspp.backbone_features.layer4.2.bn2.num_batches_tracked
missing key:  resnet_aspp.aspp.aspp1.bn.num_batches_tracked
missing key:  resnet_aspp.aspp.aspp2.bn.num_batches_tracked
missing key:  resnet_aspp.aspp.aspp3.bn.num_batches_tracked
missing key:  resnet_aspp.aspp.aspp4.bn.num_batches_tracked
missing key:  resnet_aspp.aspp.global_avg_pool.2.num_batches_tracked
missing key:  resnet_aspp.aspp.bn1.num_batches_tracked
missing key:  resnet_aspp.last_conv.1.num_batches_tracked
missing key:  resnet_aspp.last_conv.4.num_batches_tracked
loaded pre-trained weights.
progress 0/1

**Comment by zwjyongyong** [comment]
你好，请问你在运行inference.py 遇到过AssertionError: dataset/flow_visual/DAVIS/480p/blackswan/00024.jpg does not exist的问题吗?我运行flownet2-pytorch生成flo，只有23呀

**Comment by lhaof** [comment]
The keys with 'num_batches_tracked' can be ignored. See the following code.

def load_pretrain_model(net, model_path):
    net_keys = list(net.state_dict().keys())
    model = torch.load(model_path)
    model_keys = list(model.keys())
    # clean keys
    model_keys = [key for key in model_keys if not key.endswith('num_batches_tracked')]
    i = 0
    while i < len(model_keys):
        model_key_i = model_keys[i]
        net_key_i = net_keys[i]
        assert net.state_dict()[net_key_i].shape == model[model_key_i].shape, ('{}.shape: {}, {}.shape: {}'.format(net_key_i, net.state_dict()[net_key_i].shape, model_key_i, model[model_key_i].shape))
        net.state_dict()[net_key_i].copy_(model[model_key_i].cpu())
        i += 1
    return net
