### ISSUE TITLE
Download PreTrained Model

### ISSUE THREAD

**Issue by Syphixs** [lhaof/Motion-Guided-Attention#5]
Sadly I cannot download the pre-trained models from pan.baidu. From my country, I can not even register an account with my tel-number.
Is there anyway u can provide another way to download the weights?

**Comment by lhaof** [comment]
> 
> 
> Sadly I cannot download the pre-trained models from pan.baidu. From my country, I can not even register an account with my tel-number.
> Is there anyway u can provide another way to download the weights?

Google Download Link: https://drive.google.com/file/d/1tuG_S5nIAEfigKNPPsOo7SG-iIWo3T4N/view?usp=sharing
